http://127.0.0.1:8080/captive-portal?fas=NnVkOE44Z0FyV0VsbWlDa0IxUjVESXdhMHlYQVpQOWpOQ050eWQ0WlJvT3ZrR1JReThsdWx4eGJ5WmhUc3NKTmRCSzNZdFRoU2VHYkQ5eXBRVnFkeEg2YXozem5tZElqeGlxMFhiZmp6clZKd2ZteWFyVlo0RUhGZEgwNnY0K2d0TW92bWF0NndYNnpBTHJyM2hBNTh4N3RPNkFBcWZVL0s1ZGFIL1ptUEIwNzEwQndFYlFoM3BzS1B1VnhXS3hZZy8xdEhubTZ1RHk1YmhabitlbjRJc3J0WEhrQXdSQ09zRVBmbTdlMjJ1VDl5dXZydmVmTmJSc1BBMm9lcGlGbXcyZWZnSFpHbFJHc29Zd1BxNjBVVWxGaGIwbHZuNmcwMXZ2V254VlVraFdzTFhGN3JFTVJ1enhNNzhXWWRjZE1IR3NLaCswWjA2SFZMTWNRTmZ1Q1RDRnJFNFBzQUQ5S1VIT3pvQzhBTGZyM2lnUUZJM1ZqMTlSOVVRVEpKaTVtcHZZWmgyb2lZRU1qVGJ2ZGpPRGo4VjRDWjRBbTM5eitDMXNwdXlGRDViNkhmay9qMEtDUUxvL1E2djk4dlhrOUM0WXVNL3lydVBhcExlOCtsQmRTU0ZMVjY3VVAwWEwrN1E3TTZ2SGg2MDl1TkZJaUl1bXYwQmpTbXUzWkg5SkhLc3FvTGU0M3hwUHRUNG5CMExLRWt2Uis2RFhjUmF4OVBYbU1JS21icDBBR2NUVXRuUW9mNE5lUUpLNnN3NUplWkNlVTI1Y3hBYktTUWhxbGFkVFZ0UT09&iv=7a0b9573071fe747