// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AuthAcknowledgmentLog string
	AuthAttemptLog        string
	Gateway               string
}{
	AuthAcknowledgmentLog: "auth_acknowledgment_log",
	AuthAttemptLog:        "auth_attempt_log",
	Gateway:               "gateway",
}
